# Generated by Django 5.0.6 on 2024-05-17 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Granularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                "db_table": "granularity",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, null=True)),
                ("create_time", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("done_time", models.DateTimeField(null=True)),
                ("description", models.CharField(max_length=512, null=True)),
            ],
            options={
                "db_table": "job",
            },
        ),
        migrations.CreateModel(
            name="JobStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                "db_table": "job_status",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
                ("color", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
                ("content", models.CharField(max_length=2056, null=True)),
                ("challenge", models.CharField(max_length=2056, null=True)),
                ("feedback", models.CharField(max_length=2056, null=True)),
                ("workload", models.IntegerField(default=0, null=True)),
                (
                    "create_time",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "start_time",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "done_time",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "deadline_time",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                "db_table": "task_category",
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                "db_table": "task_status",
            },
        ),
    ]
