# Generated by Django 5.0.4 on 2024-05-08 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'granularity',
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'job_status',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('color', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('content', models.CharField(max_length=2056, null=True)),
                ('challenge', models.CharField(max_length=2056, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('done_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'task_category',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('done_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=512, null=True)),
                ('granularity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.granularity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='auth.group')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.jobstatus')),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
