# Generated by Django 5.0.6 on 2024-05-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="creater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="granularity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task.granularity",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="user.group",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task.jobstatus",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="creater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_of_creater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task.job",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="receiver",
            field=models.ManyToManyField(
                related_name="%(class)s_of_receiver", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="task.task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="%(class)s", to="task.tag"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="task.taskcategory",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task.taskstatus",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task.taskstatus"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="users",
            field=models.ManyToManyField(
                related_name="%(class)s", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
