# Generated by Django 5.0.6 on 2024-05-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
