# Generated by Django 5.0.6 on 2024-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="create_time",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline_time",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="done_time",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateField(null=True),
        ),
    ]
