# Generated by Django 5.0.4 on 2024-05-08 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
