# Generated by Django 5.0.6 on 2024-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_task_progress_task_project_alter_task_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
