# Generated by Django 5.0.6 on 2024-05-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_job_creater"),
        ("user", "0002_alter_user_emp_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="user.group",
            ),
        ),
    ]
