# Generated by Django 5.0.4 on 2024-05-08 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_test_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
