# Generated by Django 5.0.6 on 2024-05-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_task_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
    ]
