# Generated by Django 5.0.6 on 2024-05-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_remove_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="%(class)s",
                to="task.taskcategory",
            ),
        ),
    ]
