# Generated by Django 5.0.6 on 2024-05-16 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_alter_task_creater_alter_task_deadline_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="receiver",
        ),
        migrations.AddField(
            model_name="task",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_of_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
