# Generated by Django 5.0.6 on 2024-05-16 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_remove_task_receiver_task_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="create_time",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="done_time",
            field=models.DateTimeField(null=True),
        ),
    ]
