# Generated by Django 5.0.6 on 2024-05-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_alter_job_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="feedback",
            field=models.CharField(max_length=2056, null=True),
        ),
    ]
